### ISSUE TITLE
How to build your program?

### ISSUE THREAD

**Issue by lootoos** [saiko-tech/mmproxy-rs#1]
What commands will I need?
What dependencies will I need to install on debian 11?

**Comment by markus-wa** [comment]
You will need Rust + Cargo

You can build it via `cargo build --release` or just run it via `cargo run -- <<ARGS>>`

**Comment by lootoos** [comment]
You don't know the installation command for debian 11 / ubuntu 22.04 of these dependencies?

**Comment by markus-wa** [comment]
I don't use Debian or Ubuntu - please refer to either your Distro's documentation or the Rust installation instructions
