### ISSUE TITLE
Cloudflare Spectrum not supported?

### ISSUE THREAD

**Issue by Koyorice** [saiko-tech/mmproxy-rs#18]
![image](https://github.com/saiko-tech/mmproxy-rs/assets/87787929/b03645f5-0156-46f6-b709-c6c920fa23b9)
I tried both, but in the control it just shows this error:
![image](https://github.com/saiko-tech/mmproxy-rs/assets/87787929/5e216880-e241-4e19-a6ba-502a98721f0a)

**Comment by seg6** [comment]
Unfortunately, I don't have access to Cloudflare Spectrum. Could you please log the network packets using tools like WireShark or Netcat and share the details with us? This will help us in debugging the issue. Thank you.

**Comment by Koyorice** [comment]
![image](https://github.com/saiko-tech/mmproxy-rs/assets/87787929/b74e5b97-e701-406d-9075-13cd7332aeaf)
Here is the packet file I captured using tcpdump on the host.
https://drive.google.com/file/d/1X5IHP0YYIftp2tYx5p2jYBp1u-vAyiLM/view

**Comment by seg6** [comment]
Thanks, I'll review it when I have a moment. Meanwhile, could you please share a network capture when Simple Proxy Protocol is selected? It would be easier to debug since it's in ASCII format.

**Comment by Koyorice** [comment]
I asked some people later and they told me this is a limitation of Cloudflare:
https://developers.cloudflare.com/spectrum/reference/limitations
My server is Minecraft Bedrock Edition that's right.
