### ISSUE TITLE
support a range of ports in one instance mmproxy-rs

### ISSUE THREAD

**Issue by lootoos** [saiko-tech/mmproxy-rs#2]
Will such an opportunity be realized?

**Comment by markus-wa** [comment]
Currently the intention is to run a separate process for each connection

This is to prevent one connection from affecting another (e.g. crashes etc.)

**Comment by lootoos** [comment]
will this feature be added at all?

**Comment by markus-wa** [comment]
no, there are no plans to add this feature

**Comment by lootoos** [comment]
how much RAM/CPU does a ethernet 1Gbit/s program consume?

**Comment by lootoos** [comment]
go-mmproxy: [send: 20512950][recv: 352875] - how much is it in gigabytes?

**Comment by lootoos** [comment]
What processor was the test on? with how much RAM? with which disk?

**Comment by markus-wa** [comment]
The numbers above are in bytes.

You will need to do your own benchmarking to determine suitability for your use-case.
The performance depends heavily on environmental factors and your networking setup.

Alternatively you can reach out via email (mark@saiko.tech) to get an hourly quote for consulting services.

**Comment by seg6** [comment]
I believe #3 addresses most of @lootoos' questions.

**Comment by markus-wa** [comment]
thanks @brkp - merged it! :rocket:

**Comment by markus-wa** [comment]
Would be great to have a benchmark with a more limited bandwidth to see if that decreases data loss

**Comment by seg6** [comment]
It definitely does decrease the packet loss (%0 loss on 1G load). However, when the benchmark bandwidth is almost triple the capacity that go-mmproxy/mmproxy-rs can handle (10G), it is not surprising to see a high level of packet loss with UDP. In this case, it may be more informative to focus on other metrics rather than the packet loss column in the benchmark results. Should we just remove that column? @markus-wa

**Comment by markus-wa** [comment]
Yeah I think that makes sense - e.g. when testing from my machine to my VPS I have 99% package loss, because my internet connection cannot handle anywhere close to this amount of data
