### ISSUE TITLE
TCP listener doesn't scale well

### ISSUE THREAD

**Issue by seg6** [saiko-tech/mmproxy-rs#4]
Benchmarks done with [tcpkali](https://github.com/satori-com/tcpkali):
```
$ tcpkali -c 50 -T 10s -e1 'PROXY TCP4 127.0.0.1 127.0.0.1 \{connection.uid} 1122\r\n' -m 'PING\r\n' 127.0.0.1:25577

mmproxy-rs: Aggregate bandwidth: 14582.664↓, 14615.142↑ Mbps
go-mmproxy: Aggregate bandwidth: 27613.029↓, 27637.372↑ Mbps
```
Some initial profiling with strace showed that the Go runtime is making heavy use of the splice syscall while the Rust implementation has user-space buffers that the kernel copies data into, and out of ([tokio::io::copy_bidirectional](https://docs.rs/tokio/latest/tokio/io/fn.copy_bidirectional.html)).

> splice() is a [Linux](https://www.wikiwand.com/en/Linux)-specific [system call](https://www.wikiwand.com/en/System_call) that moves data between a [file descriptor](https://www.wikiwand.com/en/File_descriptor) and a pipe without a round trip to user space.

**Comment by seg6** [comment]
It appears that the Tokio library does not offer a zero-copy version of the `copy_bidirectional` function (or anything of that sort). However, there are other approaches that we can explore to achieve this functionality. I'll create a PR with benchmarks once I implement a reliable solution.

Some relevant web pages:
- https://blog.cloudflare.com/sockmap-tcp-splicing-of-the-future/
- https://lwn.net/Articles/879724/
- https://lwn.net/Articles/726917/

**Comment by markus-wa** [comment]
great find - this certainly sounds like something that would be great to improve!

**Comment by seg6** [comment]
![benchmark](https://i.imgur.com/CalDBBQ.png)

Seems like I got something decent working!

**Comment by seg6** [comment]
The patch for this is blocked because the transfer rate drops significantly after >1000 concurrent connections.

**Comment by markus-wa** [comment]
as in, it drops to under pre-patch levels?

maybe we could enable the patch by default but provide a flag to disable it :thinking:

**Comment by seg6** [comment]
500 connections for 20 seconds:

```
 go-mmproxy: 15691.075↓, 19121.487↑ Mbps
  pre-patch:   699.294↓,   485.227↑ Mbps
after-patch:  9997.560↓, 12030.486↑ Mbps
```

Although it's still significantly faster than the pre-patch version, it's slower compared to go-mmproxy, even though I'm essentially doing the same thing. This makes me think that the patch may have a subtle bug that could cause problems in the future, so I'm hesitant to push it to upstream. I think it's for the best that I do some more longer running tests to see its reliability.

**Comment by markus-wa** [comment]
I see - yeah I think we'll want to at least match the performance of go-mmproxy 👍

**Comment by lootoos** [comment]
Why don't you write a program in C/C++?
Programs such as "nginx" "envoyproxy" have been created in these languages

**Comment by markus-wa** [comment]
@lootoos mmproxy-rs has got nothing to do with either of those programs except that it can act as an upstream to proxy protocol enabled traffic.

further, if there is other software out there in C++ or any other language, you're free to use that or write your own.

As for the choice of Rust it comes down to memory safety, eliminating a whole class of bugs that can happen with programs in C or C++.

There is no material reason why C/C++ would be a better fit for this project, and in fact it was very deliberate to avoid unsafe and bloated (in the case of C++) languages. There is also interop in Rust to C/C++ to bridge any gap if it were needed.

To be fully honest - in general, as a maintanter, I find comments like yours here very unconstuctive to the project - similarly to other questions of yours that were unrelated to the project.

Please don't take this the wrong way. I'm just letting you know so you can phrase further question and comments in more constructive ways.

Cheers

**Comment by seg6** [comment]
To add what Markus said, there is no inherent advantage of C or C++ over Rust in terms of fast input/output (I/O). We are currently attempting to optimize this project by using the Tokio runtime to directly call the splice system call, which can reduce unnecessary data copying.

However, it is important to note that the difficulty in implementing this approach is not a limitation of the Rust language itself, but rather the APIs provided by Tokio that others have also found challenging to work with for zero-copy networking.

**Comment by markus-wa** [comment]
@brkp are we doing the splice syscall inside a tokio task? that could cause the perf degradation 👀

https://docs.rs/tokio/latest/tokio/task/ 

> Tasks are non-blocking. Typically, when an OS thread performs I/O or must synchronize with another thread, it blocks, allowing the OS to schedule another thread. When a task cannot continue executing, it must yield instead, allowing the Tokio runtime to schedule another task. Tasks should generally not perform system calls or other operations that could block a thread, as this would prevent other tasks running on the same thread from executing as well. Instead, this module provides APIs for running blocking operations in an asynchronous context.

**Comment by seg6** [comment]
I took extra care to be sure that we're not getting in the way of the Tokio runtime by blocking on calls to splice!

```rust
pub fn splice(r: i32, w: i32, n: usize) -> isize {
    // r and w can only belong to non-blocking socket/pipe fds
    // if we don't want to block (see man splice)
    unsafe {
        libc::splice(
            r,
            ptr::null_mut::<libc::loff_t>(),
            w,
            ptr::null_mut::<libc::loff_t>(),
            n,
            libc::SPLICE_F_MOVE | libc::SPLICE_F_NONBLOCK, // non-blocking call to splice
        )
    }
}
```

What I'm currently suspecting is that the program is just spawning way too many tasks and Tokio is having a hard time scheduling them, which in turn degrades the performance when the number of concurrent users are too high (Go is really smart with its scheduling business).

There's also [tokio-uring](https://github.com/tokio-rs/tokio-uring) that lets you do I/O in a new-ish way on Linux which might be worth exploring for this type of applications.

Anyways, I'm actively working on this and will post updates about anything worth mentioning as this issue has kinda turned into a tracking issue!

**Comment by seg6** [comment]
Okay, so it looks like I spent a lot of time searching for a bug that didn't actually exist. 

After going through the Go standard library source code, I realized that [the max pipe size](https://github.com/golang/go/blob/c8bb3cff9ee24f310f4d5dd7b39422c346411a53/src/internal/poll/splice_linux.go#L22) had [been set to 1MB](https://github.com/golang/go/blob/c8bb3cff9ee24f310f4d5dd7b39422c346411a53/src/internal/poll/splice_linux.go#L222) instead of the [default 64KB #Pipe Capacity](https://man7.org/linux/man-pages/man7/pipe.7.html). This means that the program can execute fewer syscalls because more data can be moved with a single syscall.

I'll make a few more tweaks and then submit the patch.

**Comment by lootoos** [comment]
has performance improved?

**Comment by seg6** [comment]
> has performance improved?

Yes, it's significantly faster. The README has some benchmarks.
