### ISSUE TITLE
TCP Fast Open

### ISSUE THREAD

**Issue by lootoos** [saiko-tech/mmproxy-rs#5]
will you add this function so that you can reduce the ping by 30%?
https://www.keycdn.com/support/tcp-fast-open

**Comment by markus-wa** [comment]
Just to clarify - TFO does not reduce ping by 30% in all cases - TFO only reduces latency of re-opening a previously closed connection.

It does however not affect long lasting TCP connections and it needs to be supported by the client (Nginx does seem to support it!).

We'd be happy to accept PRs implementing the suggested change :slightly_smiling_face:

**Comment by lootoos** [comment]
TCP Fast Open  from Nginx supports it seems only for site traffic, but I will have game traffic, minecraft game traffic, minecraft game also supports TCP Fast Open, only wireguard does not support TCP Fast Open, thereby TCP Fast Open does not work on the home server, although TCP Fast Open support is enabled on vds + home pc. In general, it is not enough to have TCP Fast Open support in the game itself, it is also necessary that the software supports TCP Fast Open through which the packet(s) passes before it gets to minecraft server

**Comment by markus-wa** [comment]
I can't find any documentation that Minecraft supports TFO - do you have any link for this?

**Comment by lootoos** [comment]
yes, https://docs.papermc.io/velocity/configuration , 
![ScreenShot_20221218205130](https://user-images.githubusercontent.com/109325265/208311983-0cb7fdba-dfe1-4929-b86a-9c2b1c1684aa.png)
![ScreenShot_20221218205154](https://user-images.githubusercontent.com/109325265/208311984-79254f79-4c0f-4d37-884b-9e8491371bd7.png)

**Comment by seg6** [comment]
It seems that Velocity already supports proxy-protocol, and as far as I know, HAProxy implements TFO. mmproxy-rs is meant to be used when you are unable to add proxy-protocol support to your target application. What's your use case for mmproxy-rs? @lootoos

**Comment by lootoos** [comment]
HAProxy does not support the "UDP" protocol?

**Comment by lootoos** [comment]
mmproxy-rs I need it so that my network can receive normal IPV4 addresses of minecraft server players

**Comment by seg6** [comment]
Isn't Minecraft TCP-only? You should be able to have either NGINX or HAProxy directly target Velocity (proxy protocol feature enabled) and get TFO for free along the way.

**Comment by lootoos** [comment]
I need another protocol "UDP", only "TCP" will not suit me, I will run a thousand minecraft servers because I rent them out, only buyers never know what a "proxy-protocol" is, so I will use mmproxy-rs so that servers can extract normal ipv4 packets.

**Comment by seg6** [comment]
I see, yeah, it would be great to have support for TFO in mmproxy-rs. However, my current priority is optimizing the TCP proxy to be zero-copy, so introducing TFO will have to wait for that. Unless someone else takes on the task of implementing TFO, it may take some time before it is introduced.

**Comment by lootoos** [comment]
> Isn't Minecraft TCP-only? You should be able to have either NGINX or HAProxy directly target Velocity (proxy protocol feature enabled) and get TFO for free along the way.

I would do so, but the noobs clients no are in the business of configuring the server, so they don't even know that there is such a function, it's better if you add TFO to mmproxy-rs

**Comment by seg6** [comment]
Since this issue has become inactive, I will go ahead and close it. Feel free to reopen it if you'd like to continue the discussion further.
